services:
  app:
    image: guru-api:latest
    container_name: guru-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    ports:
      - '${APP_PORT}:3000'
      - '${SSH_PORT}:22'
    environment:
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - SUPABASE_PORT=6543
      - SUPABASE_USERNAME=postgres.crilujirdfczplpdeltx
      - SUPABASE_PASSWORD=QTvCftteCv84ekzR
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - HOSTED_SUPABASE_JWT_SECRET=${HOSTED_SUPABASE_JWT_SECRET}
      - HOSTED_SUPABASE_HOST=157.173.121.95
      - HOSTED_SUPABASE_PORT=6543
      - HOSTED_SUPABASE_USERNAME=postgres.guruu
      - HOSTED_SUPABASE_PASSWORD=password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
